# number 5 to run code just using pytest no -v -s needed

[pytest]

markers =
    sanity
    regression
# number 7 - updated adopts with html path
addopts = -v -s --html=reporttss/report.html

python_files = test_*.py
python_classes = Test*
python_functions = test_*
